maintainer: Frank,H.L.Lai
data:
  dataset: FF48 # FF48, FF100
  period: # string for year and month
    start: '197501'
    end: '202412'
  frequency: Daily # Monthly / Weekly / Daily
parameter:
  window_size: 120
  cutoff: 5
algorithm:
  ucb: True
  psr: True
  psr-ucb: True
  pw-ucb: True